theme = "vistor"

[editor]
scrolloff = 8
middle-click-paste = false
line-number = "relative"
continue-comments = false

[editor.statusline]
left = ["mode", "file-name", "file-modification-indicator", "spinner"]
center = ["read-only-indicator", "diagnostics"]
right = ["position-percentage", "file-type"]
separator = "│"
mode.normal = "normal"
mode.insert = "insert"
mode.select = "select"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.soft-wrap]
enable = true


[keys.normal]
"X" = "select_line_above"

[keys.normal.g]
"v" = ["vsplit", "goto_definition"] # go to definition in a vertical split
